### PR TITLE
Alex added key

### PR DESCRIPTION
**Pull request by zandercreations**

### CODE REVIEW

**Review by ysibirski — CHANGES_REQUESTED** [review]
Looks good Alex but you are missing one identity in you GPG key
$ gpg --show-keys --with-fingerprint 0A46660F6984747676D3B0F16066501F4B4E066A.asc 

> pub   rsa4096 2022-10-21 [SC]
      0A46 660F 6984 7476 76D3  B0F1 6066 501F 4B4E 066A
uid                      Alex Hill <ahill@zensystem.io>
uid                      Alex Hill <ahill@horizenlabs.io>
sub   rsa4096 2022-10-21 [E]


ahill@horizen.io is missing. I do not think it will be an immediate issue, but may pop up at some point

**Comment by zandercreations** [comment]
> Looks good Alex but you are missing one identity in you GPG key $ gpg --show-keys --with-fingerprint 0A46660F6984747676D3B0F16066501F4B4E066A.asc
> 
> > pub   rsa4096 2022-10-21 [SC]
> > 0A46 660F 6984 7476 76D3  B0F1 6066 501F 4B4E 066A
> > uid                      Alex Hill [ahill@zensystem.io](mailto:ahill@zensystem.io)
> > uid                      Alex Hill [ahill@horizenlabs.io](mailto:ahill@horizenlabs.io)
> > sub   rsa4096 2022-10-21 [E]
> 
> [ahill@horizen.io](mailto:ahill@horizen.io) is missing. I do not think it will be an immediate issue, but may pop up at some point

I never got an invite to setup an email under that domain.

**Comment by ysibirski** [comment]
> > Looks good Alex but you are missing one identity in you GPG key $ gpg --show-keys --with-fingerprint 0A46660F6984747676D3B0F16066501F4B4E066A.asc
> > > pub   rsa4096 2022-10-21 [SC]
> > > 0A46 660F 6984 7476 76D3  B0F1 6066 501F 4B4E 066A
> > > uid                      Alex Hill [ahill@zensystem.io](mailto:ahill@zensystem.io)
> > > uid                      Alex Hill [ahill@horizenlabs.io](mailto:ahill@horizenlabs.io)
> > > sub   rsa4096 2022-10-21 [E]
> > 
> > 
> > [ahill@horizen.io](mailto:ahill@horizen.io) is missing. I do not think it will be an immediate issue, but may pop up at some point
> 
> I never got an invite to setup an email under that domain.

It is an alias for `zensystem.io` domain

**Review by ysibirski — APPROVED** [review]
LGTM

**Pull request merged**
